//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WallOfHonor.WOHWebPart {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class WOHWebPart {
        
        public static implicit operator global::System.Web.UI.TemplateControl(WOHWebPart target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::WallOfHonor.WOHWebPart.WOHWebPart @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n<link type=\"text/css\" rel=\"stylesheet\" href=\"../_layouts/15/WallOfHonor/Sou" +
                        "rce/semantic/dist/semantic.min.css\" />\r\n<link type=\"text/css\" rel=\"stylesheet\" h" +
                        "ref=\"../_layouts/15/WallOfHonor/Source/css/dialogStyle.css\" />\r\n<link type=\"text" +
                        "/css\" rel=\"stylesheet\" href=\"../_layouts/15/WallOfHonor/Source/css/main.css\" />\r" +
                        "\n<link type=\"text/css\" rel=\"stylesheet\" href=\"../_layouts/15/WallOfHonor/Source/" +
                        "touch/touchTouch.css\" />\r\n\r\n<script type=\"text/javascript\" src=\"../_layouts/15/W" +
                        "allOfHonor/Source/js/jquery-1.11.3.min.js\"></script>\r\n<script type=\"text/javascr" +
                        "ipt\" src=\"../_layouts/15/WallOfHonor/Source/semantic/dist/semantic.min.js\"></scr" +
                        "ipt>\r\n<script type=\"text/javascript\" src=\"../_layouts/15/WallOfHonor/Source/js/d" +
                        "ialog.js\"></script>\r\n<script type=\"text/javascript\" src=\"../_layouts/15/WallOfHo" +
                        "nor/Source/js/main.js\"></script>\r\n<script type=\"text/javascript\" src=\"../_layout" +
                        "s/15/WallOfHonor/Source/touch/touchTouch.jquery.js\"></script>\r\n<script type=\"tex" +
                        "t/javascript\" src=\"../_layouts/15/WallOfHonor/Source/js/nailthumb.min.js\"></scri" +
                        "pt>\r\n\r\n<div class=\"ui segment\">\r\n    <div class=\"ui selection dropdown field\" id" +
                        "=\"divDeparts\">\r\n        <input type=\"hidden\" name=\"nomination\">\r\n        <i clas" +
                        "s=\"dropdown icon\"></i>\r\n        <div id=\"defDepart\" class=\"default text\">Выберит" +
                        "е подразделение</div>\r\n        <div class=\"menu\">\r\n            <div class=\"item\"" +
                        " data-value=\"dep1\" data-text=\"Все департаменты\">\r\n                Все департамен" +
                        "ты\n               \r\n            </div>\r\n            <div class=\"item\" data-value" +
                        "=\"dep2\" data-text=\"Департамент маркетинга\">\r\n                Департамент маркети" +
                        "нга\n               \r\n            </div>\r\n            <div class=\"item\" data-valu" +
                        "e=\"dep3\" data-text=\"Департамент продаж\">\r\n                Департамент продаж\n   " +
                        "            \r\n            </div>\r\n            <div class=\"item\" data-value=\"dep4" +
                        "\" data-text=\"Департамент IT\">\r\n                Департамент IT\n               \r\n " +
                        "           </div>\r\n            <div class=\"item\" data-value=\"dep5\" data-text=\"Де" +
                        "партамент финансов\">\r\n                Департамент финансов\n               \r\n    " +
                        "        </div>\r\n        </div>\r\n    </div>\r\n    <div id=\"adminPanel\" class=\"cust" +
                        "om-seg hiddenseg\" style=\"display: none\">\r\n        <div class=\"ui selection dropd" +
                        "own field custom-fld\" id=\"divBorder\">\r\n            <input type=\"hidden\" name=\"bo" +
                        "rderType\">\r\n            <i class=\"dropdown icon\"></i>\r\n            <div id=\"defB" +
                        "order\" class=\"default text\">Тип рамки</div>\r\n            <div class=\"menu\">\r\n   " +
                        "             <div class=\"item\" data-value=\"nom1\" data-text=\"Портретная\">\r\n      " +
                        "              <img src=\"../_layouts/15/WallOfHonor/Source/img/ramka.jpg\">Портрет" +
                        "ная\n               \r\n                </div>\r\n                <div class=\"item\" d" +
                        "ata-value=\"nom2\" data-text=\"Без рамки\">\r\n                    <img src=\"../_layou" +
                        "ts/15/WallOfHonor/Source/img/noborder.png\">Без рамки\n               \r\n          " +
                        "      </div>\r\n            </div>\r\n        </div>\r\n        <div class=\"ui selecti" +
                        "on dropdown field custom-fld\" id=\"divImageSize\">\r\n            <input type=\"hidde" +
                        "n\" name=\"imageSize\">\r\n            <i class=\"dropdown icon\"></i>\r\n            <di" +
                        "v id=\"defImage\" class=\"default text\">Размер фото</div>\r\n            <div class=\"" +
                        "menu\">\r\n                <div class=\"item\" data-value=\"nom1\" data-text=\"Маленький" +
                        "\">\r\n                    Маленький\n               \r\n                </div>\r\n     " +
                        "           <div class=\"item\" data-value=\"nom2\" data-text=\"Средний\">\r\n           " +
                        "         Средний\n               \r\n                </div>\r\n                <div c" +
                        "lass=\"item\" data-value=\"nom3\" data-text=\"Большой\">\r\n                    Большой\n" +
                        "               \r\n                </div>\r\n            </div>\r\n        </div>\r\n   " +
                        "     <div class=\"rightpos\">\r\n            <button type=\"button\" class=\"ui primary" +
                        " button\" id=\"saveProps\">\r\n                Сохранить\n           \r\n            </b" +
                        "utton>\r\n            <button type=\"button\" class=\"ui button\" id=\"delUsers\">\r\n    " +
                        "            Удалить всех\n           \r\n            </button>\r\n        </div>\r\n   " +
                        " </div>\r\n</div>\r\n<div class=\"thumbs\" id=\"mainThumbs\">\r\n    <!--Здесь будет datas" +
                        "ource-->\r\n    \r\n    <!---->\r\n</div>\r\n<div class=\"ui modal form custom-form\">\r\n  " +
                        "  <i class=\"close icon\"></i>\r\n    <div class=\"header\" id=\"modalHeader\">Добавлени" +
                        "е сотрудника на доску почета</div>\r\n    <div class=\"content\">\r\n        <div clas" +
                        "s=\"field\">\r\n            <label>ФИО сотрудника</label>\r\n            <div class=\"u" +
                        "i input\">\r\n                <input type=\"text\" id=\"fioUser\" placeholder=\"Введите " +
                        "ФИО сотрудника\" required>\r\n            </div>\r\n        </div>\r\n        \r\n       " +
                        " <div class=\"field\">\r\n            <label>Департамент</label>\r\n            <div c" +
                        "lass=\"ui selection dropdown\">\r\n                <input type=\"hidden\" name=\"depart" +
                        "ment\">\r\n                <i class=\"dropdown icon\"></i>\r\n                <div id=\"" +
                        "depUser\" class=\"default text\">Выберите подразделение</div>\r\n                <div" +
                        " class=\"menu\">\r\n                    <div class=\"item\" data-value=\"dep1\" data-tex" +
                        "t=\"Департамент маркетинга\">\r\n                        Департамент маркетинга\r\n   " +
                        "                 </div>\r\n                    <div class=\"item\" data-value=\"dep2\"" +
                        " data-text=\"Департамент продаж\">\r\n                        Департамент продаж    " +
                        "               \r\n                    </div>\r\n                    <div class=\"ite" +
                        "m\" data-value=\"dep3\" data-text=\"Департамент IT\">\r\n                        Департ" +
                        "амент IT\r\n                    </div>\r\n                    <div class=\"item\" data" +
                        "-value=\"dep4\" data-text=\"Департамент финансов\">\r\n                        Департа" +
                        "мент финансов\n                   \r\n                    </div>\r\n                <" +
                        "/div>\r\n            </div>\r\n        </div>\r\n        <div class=\"field\">\r\n        " +
                        "    <label>Должность</label>\r\n            <div class=\"ui input\">\r\n              " +
                        "  <input type=\"text\" id=\"posUser\" placeholder=\"Введите должность\" required>\r\n   " +
                        "         </div>\r\n        </div>\r\n        <div class=\"field\">\r\n            <label" +
                        ">Номинация</label>\r\n            <div class=\"ui selection dropdown field\">\r\n     " +
                        "           <input type=\"hidden\" name=\"nomination\">\r\n                <i class=\"dr" +
                        "opdown icon\"></i>\r\n                <div id=\"defNom\" class=\"default text\">Выберит" +
                        "е номинацию</div>\r\n                <div class=\"menu\">\r\n                    <div " +
                        "class=\"item\" data-value=\"nom1\" data-text=\"Лучший менеджер\">\r\n                   " +
                        "     <i class=\"trophy icon\"></i>Лучший менеджер\n                   \r\n           " +
                        "         </div>\r\n                    <div class=\"item\" data-value=\"nom2\" data-te" +
                        "xt=\"Лучший маркетолог\">\r\n                        <i class=\"trophy icon\"></i>Лучш" +
                        "ий маркетолог\n                   \r\n                    </div>\r\n                 " +
                        "   <div class=\"item\" data-value=\"nom3\" data-text=\"Лучший консультант\">\r\n        " +
                        "                <i class=\"trophy icon\"></i>Лучший консультант\n                  " +
                        " \r\n                    </div>\r\n                    <div class=\"item\" data-value=" +
                        "\"nom4\" data-text=\"Лучший маркетинговый проект\">\r\n                        <i clas" +
                        "s=\"trophy icon\"></i>Лучший маркетинговый проект\n                   \r\n           " +
                        "         </div>\r\n                    <div class=\"item\" data-value=\"nom5\" data-te" +
                        "xt=\"Лучший региональный проект года\">\r\n                        <i class=\"trophy " +
                        "icon\"></i>Лучший региональный проект года\n                   \r\n                 " +
                        "   </div>\r\n                    <div class=\"item\" data-value=\"nom6\" data-text=\"Лу" +
                        "чший продукт менеджер\">\r\n                        <i class=\"trophy icon\"></i>Лучш" +
                        "ий продукт менеджер\n                   \r\n                    </div>\r\n           " +
                        "         <div class=\"item\" data-value=\"nom7\" data-text=\"Самый креативный сотрудн" +
                        "ик\">\r\n                        <i class=\"trophy icon\"></i>Самый креативный сотруд" +
                        "ник\n                   \r\n                    </div>\r\n                    <div cl" +
                        "ass=\"item\" data-value=\"nom8\" data-text=\"Самый ответственный сотрудник\">\r\n       " +
                        "                 <i class=\"trophy icon\"></i>Самый ответственный сотрудник\n      " +
                        "             \r\n                    </div>\r\n                </div>\r\n            <" +
                        "/div>\r\n        </div>\r\n        <div class=\"field\">\r\n            <label>Достижени" +
                        "е</label>\r\n            <div class=\"ui selection dropdown\">\r\n                <inp" +
                        "ut type=\"hidden\" name=\"achivement\">\r\n                <i class=\"dropdown icon\"></" +
                        "i>\r\n                <div id=\"defAch\" class=\"default text\">Выберите достижение</d" +
                        "iv>\r\n                <div class=\"menu\">\r\n                    <div class=\"item\" d" +
                        "ata-value=\"ach1\" data-text=\"За большие достижения в бизнесе\">\r\n                 " +
                        "       За большие достижения в бизнесе\r\n                    </div>\r\n            " +
                        "        <div class=\"item\" data-value=\"ach2\" data-text=\"За достижение высокого пр" +
                        "офессионализма\">\r\n                        За достижение высокого профессионализм" +
                        "а\n                   \r\n                    </div>\r\n                    <div clas" +
                        "s=\"item\" data-value=\"ach3\" data-text=\"За вклад в продвижение продаж\">\r\n         " +
                        "               За вклад в продвижение продаж\r\n                    </div>\r\n      " +
                        "              <div class=\"item\" data-value=\"ach4\" data-text=\"За многолетний добр" +
                        "осовестный труд\">\r\n                        За многолетний добросовестный труд\n  " +
                        "                 \r\n                    </div>\r\n                    <div class=\"i" +
                        "tem\" data-value=\"ach5\" data-text=\"За высокие показатели в работе\">\r\n            " +
                        "            За высокие показатели в работе\r\n                    </div>\r\n        " +
                        "        </div>\r\n            </div>\r\n        </div>\r\n\r\n        <!--Альтернатива--" +
                        ">\r\n        <div class=\"field\">\r\n            <div class=\"ui action input\">\r\n     " +
                        "           <input type=\"text\" id=\"_attachmentName\">\r\n                <label for=" +
                        "\"attachmentName\" class=\"ui icon button btn-file\">\r\n                    <i class=" +
                        "\"cloud upload icon\"></i>\r\n                    <input type=\"file\" id=\"attachmentN" +
                        "ame\" name=\"attachmentName\" style=\"display: none\">\r\n                </label>\r\n   " +
                        "         </div>\r\n        </div>\r\n        <!---->\r\n        <div class=\"actions\">\r" +
                        "\n            <div class=\"ui positive right labeled icon button custom-button\">\r\n" +
                        "                Сохранить\n              \r\n                <i class=\"checkmark ic" +
                        "on\"></i>\r\n            </div>\r\n            <div class=\"ui cancel button\">\r\n      " +
                        "          Отмена\n               \r\n            </div>\r\n        </div>\r\n    </div>" +
                        "\r\n</div>\r\n"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
